### ISSUE TITLE
Player kill volume isn't really killing anyone

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#441]
Not sure if its a bug or that was made for some purpose, but when player touches kill volume - he doesn't die instantly and only loses some HP. Might be also because of armors? But I suppose it should ignore armors? By the way, when testing map on singleplayer - everything works perfect - I die instantly after touching kill volume

Also, it doesn't do any damage for player in vehicle

**Comment by SDGNelson** [comment]
Looks like the damage is routed through DamageTool.damage which takes into account the playerDamaged event and server config's modeConfigData.Players.Armor_Multiplier. Maybe the damage should be dealt directly to PlayerLife? Does anyone's plugins rely on modifying KillVolume damage?

**Comment by baranmod** [comment]
Ok, thats really due to armor_multiplier. I've tested without any plugins and set armor multiplier to 0.85 - didn't die (16HP left), then set armor multiplier to default (1.0) - works like a charm

**Comment by SDGNelson** [comment]
For the next version I'll change kill volumes to damage players directly.

Currently the vehicle demo is only up for a few players because feature wise it's barebones, but if you give me your email I can send you a key.

**Comment by baranmod** [comment]
Ohh, cool, would love to test that :) baran.modestas@gmail.com thanks!

**Comment by VitaxaRusModding** [comment]
@SDGNelson  Please can I access? =) My mail: stopgame.2015@yandex.ru

**Comment by aviadmini** [comment]
Didn't KillVolume deal 20k damage?

**Comment by baranmod** [comment]
One more bug with kill volume - it doesn't work when player is in vehicle.

**Comment by educatalan02** [comment]
There is another bug like that, when you put one object upside down. When the players are walking over the object they die by the way. I tested it with a bunker.

**Comment by SDGNelson** [comment]
Both bugs should be fixed in the next update.

**Comment by baranmod** [comment]
Volume still doesn't kill (16 HP left with 0.85 armor multiplier)
